version: "2"
services:
  db:
    image: sensebox/opensensemap-api-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - api-db-network

  jobs:
    build: './outliers/'
    depends_on:
      - db
    links:
      - db
      - redis
    networks:
      - api-db-network

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'
    networks:
      - api-db-network

volumes:
  mongo-data:
networks:
  api-db-network:
    external: true
